name: test

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/liatapp
      - name: tests to deploy
      - name: run image
        run: docker run -dp 80:8080 ${{secrets.DOCKER_USERNAME}}/liatapp
      - name: liat tests
        uses: liatrio/github-actions/apprentice-action@921d5abcef26851810ca11a97e1418c1c3f95e0b
      - name: login docker
        env:
            DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASS: ${{secrets.DOCKER_PASSWORD}}
        run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - name: push docker hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/liatapp

