name: test

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/liatapp
  test-deploy:
    name: tests to deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: run image
        run: docker run -d -p 80:80 ${{secrets.DOCKER_USERNAME}}/liatapp
      - name: liat tests
        uses: liatrio/github-actions/apprentice-action@master
      - name: login docker
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: push docker hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/liatapp

